name: Android Build (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # ✅ ম্যানুয়ালি চালানোর অপশন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Create output folder
        run: mkdir -p output

      - name: Copy APK to output folder
        run: cp app/build/outputs/apk/debug/app-debug.apk output/app-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: output/app-debug.apk
