name: Android Build (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install required build tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detect module path
        id: detect
        run: |
          MODULE_PATH=$(find . -type f -name "build.gradle*" -exec dirname {} \; | grep -vE "gradle/wrapper|\\." | head -n 1)
          echo "Detected module: $MODULE_PATH"
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV

      - name: Build Debug APK
        run: ./gradlew :${{ env.MODULE_PATH##*/ }}:assembleDebug --stacktrace --info

      - name: Create output folder
        run: mkdir -p output

      - name: Copy APK to output folder
        run: |
          APK_PATH=$(find $MODULE_PATH/build/outputs -name "*.apk" | head -n 1)
          if [ -f "$APK_PATH" ]; then
            cp "$APK_PATH" output/app-debug.apk
            echo "✅ APK found and copied successfully!"
          else
            echo "❌ APK not found. Build may have failed."
            ls -R $MODULE_PATH/build || true
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: output/app-debug.apk
