name: Android Build (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # ✅ ম্যানুয়ালি চালানোর অপশন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Create output folder
        run: mkdir -p output

      - name: Copy APK to output folder
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            cp app/build/outputs/apk/debug/app-debug.apk output/app-debug.apk
          else
            echo "❌ APK not found!"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: output/app-debug.apk
